version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13  
    container_name: postgres_db
    environment:
      POSTGRES_USER: user    
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: movie_db  
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  


volumes:
  postgres_data:
    driver: local
networks:
  app-network:
    driver: bridge

